# Swift 5.4, SwiftLint 0.43.1

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  # - function_body_length
  - identifier_name
  - line_length
  - nesting
  - object_literal
  - redundant_string_enum_value # This exception is needed to allow Codable enums case names that match their raw value, but may diverge in the future if the API they're decoded from changes its parameter names/values.
  # - todo
  - trailing_whitespace
  # - type_name
  - xctfail_message

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - capture_variable
  # - closure_body_length
  # - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  # - explicit_acl
  # - explicit_enum_raw_value
  - explicit_init
  - explicit_self
  # - explicit_top_level_acl
  # - explicit_type_interface
  # - extension_access_modifier
  # - fallthrough
  # - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  ## - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  # - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  # - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  # - no_extension_access_modifier
  # - no_grouping_extension
  - nslocalizedstring_key
  # - nslocalizedstring_require_bundle
  - number_separator
  # - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  # - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  # - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  # - prohibited_interface_builder
  - prohibited_super_call
  # - quick_discouraged_call
  # - quick_discouraged_focused_test
  # - quick_discouraged_pending_test
  # - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  # - redundant_type_annotation
  # - required_deinit
  # - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  # - strong_iboutlet
  # - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  #  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Carthage
  - fastlane
  - FRCircleTests
  - Pods
  - Packages
  - vendor

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@IBInspectable", "@objc"]
  always_on_line_above:
    ["@IBDesignable", "@UIApplicationMain", "@discardableResult"]

# configurable rules can be customized from this configuration file
identifier_name:
  min_length: # only min_length
    warning: 1 # only error
  max_length:
    warning: 40
    error: 60
  excluded: # excluded via string array
    - id
type_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 60
overridden_super_call:
  excluded:
    - "**/.*Tests\\.swift"
# force_unwrapping: error

indentation: tabs

function_parameter_count:
  - 6 # warning
  - 8 # error
function_body_length:
  - 80 # warning
  - 160 # error
type_body_length:
  - 400 # warning
  - 500 # error

custom_rules:
  # disable_rule:
  #   name: "Disable Rule In Code"
  #   regex: "(swiftlint:disable)"
  #   message: "Do not disable rule in code. "
  #   severity: error
  #   match_kinds: comment
  #   excluded: "Toranoko/Common/Helpers/SwiftGen/.*\\.swift" # regex that defines paths to exclude during linting. optional
  outlet_collection:
    name: "outlet_collection"
    regex: "(@IBOutletCollection)"
    message: "IBOutletCollection is not permitted. "
    severity: error
  comments_space:
    name: "Add Space After Comment"
    regex: "(^\\s*//\\w+)"
    message: "There should be a space after //"
    severity: warning
    match_kinds: comment

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
